tls_server_config:
  client_auth_type: "NoClientCert"
  cert_file: /usr/share/prometheus/certs/prometheus/prometheus.crt
  key_file: /usr/share/prometheus/certs/prometheus/prometheus.key
  #client_auth_type: "RequireAndVerifyClientCert"
  #client_ca_file: /usr/share/prometheus/certs/ca/ca.crt
